In [39]:
import sys
import numpy as np


In [40]:
array_1d = np.array([4,5,6])
type(array_1d)

numpy.ndarray

In [41]:
array_1d.ndim

1

In [42]:
array_1d.shape

(3,)

In [43]:
matriz = np.array([[1,2],[3,4]]) #Creamos una matriz de dos dimensiones

In [44]:
matriz.ndim #Nos indica las dimensiones de la matriz

2

In [45]:
matriz.shape #nos indica la forma de la matriz, 2x2 en este caso 

(2, 2)

In [46]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [47]:
np.eye(2) #MATRIZ IDENTIDAD 

array([[1., 0.],
       [0., 1.]])

In [48]:
np.random.random([3,3]) #Crea una matriz 3x3 con numeros random de 0-1

array([[0.68296859, 0.50243844, 0.44105784],
       [0.95928693, 0.60280811, 0.96560828],
       [0.02914324, 0.5837045 , 0.70035455]])

In [49]:
!cat matriz3x3.txt #Mostramos el texto dentro del archivo matriz3x3.txt

1,2,3
4,5,6
7,8,9


In [50]:
np_text = np.genfromtxt("matriz3x3.txt",delimiter=",") #Creamos el array desde el archivo .txt
# y colocamos como delimitador las comas 
np_text

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [51]:
#Aqui se muestran las diferencias entre crear una lista 2d y un array 2d 
lista_2d = ([1,2,3],[4,5,6]) #Creamos una lista 2d
print(lista_2d)
array_2d = np.array([[1,2,3],[4,5,6]]) # Creamos un array 
array_2d 

([1, 2, 3], [4, 5, 6])


array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
big_lista = list([range(10)])
big_array = np.array(range(10))
print(big_lista,big_array)

[range(0, 10)] [0 1 2 3 4 5 6 7 8 9]


In [63]:

%%timeit -r 3 -n 100
sum(range(1000000))

13.2 ms ± 146 µs per loop (mean ± std. dev. of 3 runs, 100 loops each)


In [64]:
%%timeit -r 3 -n 100
np.sum(np.arange(1000000))

705 µs ± 16.5 µs per loop (mean ± std. dev. of 3 runs, 100 loops each)


In [68]:
array = np.array(([1,2,3],[4,5,6],[7,8,9]))
print(array)
array [1,1]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


5

In [75]:
print(array[2:3])
print("--------------------")
print(array[:1])
print("--------------------")
print(array[:2])

[[7 8 9]]
--------------------
[[1 2 3]]
--------------------
[[1 2 3]
 [4 5 6]]


In [78]:
matriz_32 = np.array(([1,2],[2,3],[2,5]))
matriz_32

array([[1, 2],
       [2, 3],
       [2, 5]])

In [81]:
filtrado = matriz_32 > 2
filtrado

array([[False, False],
       [False,  True],
       [False,  True]])

In [82]:
matriz_32[filtrado]


array([3, 5])

In [84]:
array1 = np.array(([1,1],[2,2]))
array2 = np.array(([2,2],[3,3]))
array1*array2 #esta multiplicacion solo multiplica los numeros de la misma casilla no es una multiplicacion de matrices


array([[2, 2],
       [6, 6]])

In [85]:
array1 @ array2 #multiplicacion matricial 

array([[ 5,  5],
       [10, 10]])